# ES-24674

## Stacktrace

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.elasticsearch.search.fetch.subphase.highlight.FastVectorHighlighter.highlight(FastVectorHighlighter.java:91)
	at org.elasticsearch.search.fetch.subphase.highlight.HighlightPhase.hitExecute(HighlightPhase.java:124)
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:163)
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:294)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:271)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:618)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:613)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
```

## Frame 1
The target method is in a `try` block, followed by `catch(Exception e)`. Inside the catch block, a custom exception called `FetchPhaseExecutionException` is raised.
The target method has *141* lines of code.
Target line is not covered by EvoCrash tests.

## Frame 2
The target method has *79* lines of code. EvoCrash tests do not reach the target line through the generated input arguments.

## Frame 3
The target method has *80* lines of code. The tests from EvoCrash reach 1.5 line coverage, so the final fitness is 4.5
## Frame 4
The target method is private, and called by the method in the next frame. The target line is inside a `try` block, followed by a `catch(Exception e)`. No exception would be raised at this level.

```
    private QueryFetchSearchResult executeFetchPhase(SearchContext context, SearchOperationListener operationListener,
                                                        long afterQueryTime) {
        operationListener.onPreFetchPhase(context);
        try {
            shortcutDocIdsToLoad(context);
            fetchPhase.execute(context);
            if (fetchPhaseShouldFreeContext(context)) {
                freeContext(context.id());
            } else {
                contextProcessedSuccessfully(context);
            }
        } catch (Exception e) {
            operationListener.onFailedFetchPhase(context);
            throw ExceptionsHelper.convertToRuntime(e);
        }
        operationListener.onFetchPhase(context, System.nanoTime() - afterQueryTime);
        return new QueryFetchSearchResult(context.queryResult(), context.fetchResult());
    }
```
Guided initialization fails at this level.
## Frame 5
The target method at this level is public. It is also inside a `try` block, followed by `catch(Exception e)`. So no exception would be raised at this level either.
This frame points to the same class as referred to at frame 4. For the same reason, guided initialization fails at this level as well.
## Frame 6
This frame points to an anonymous class which is not supported by EvoCrash.
## Frame 7
This frame points to the line where the anonymous class is defined in the previous frame. This frame is useless to crash reproduction.
## Frame 8
Guided initialization fails at this level.
## Frame 9
Points to an anonymous class, not supported by EvoCrash.
## Frame 10
The target line is inside a private inner class. This is not supported by EvoSuite.
## Frame 11
The target class is abstract. In addition, the target line is inside a `try` block, followed by a `catch(Exception t)` block. If an exception occurs, it is signaled to other components. So no exception is thrown during program executions at this level.
```
    @Override
    public final void run() {
        try {
            doRun();
        } catch (Exception t) {
            onFailure(t);
        } finally {
            onAfter();
        }
    }
```
